name = "multi-app-in-routes"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "dist/apps"
entry-point = "app-shell"

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

[env.production]
workers_dev = false
route = "multi-app-in-routes.pages.dev/*"
zone_id = ""

# Configure routes for each micro-frontend
[[routes]]
pattern = "/hr/*"
script = "hr/index.html"

[[routes]]
pattern = "/timeMangment/*"
script = "timeMangment/index.html"

[[routes]]
pattern = "/calandar/*"
script = "calandar/index.html"

[[routes]]
pattern = "/tracker/*"
script = "tracker/index.html"

[[routes]]
pattern = "/projects/*"
script = "projects/index.html"

[[routes]]
pattern = "/*"
script = "app-shell/index.html"
